# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb514000b3671596d02e6791d3e51666eaa22f8a830043de2f31073ac04f897d05ffddbfe7f116bb58d21bf7042653c58a26eaa8358942cbfa4d155daa9cf338

test:
  secret_key_base: b7c682d6d6b4ae138f5ec2397b0f26c5be0d458833c415218399a089ed42b15b24a5ad4b7b4cde7900bce8f323a98dfc064687425ee849a3b44945119eb52805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
